const STOPWORDS = new Set([
  "a", "an", "the", "i", "me", "my", "we", "our", "you", "your",
  "he", "she", "it", "they", "them", "his", "her", "its", "their",
  "this", "that", "these", "those", "who", "whom", "which", "what",
  "am", "is", "are", "was", "were", "be", "been", "being",
  "have", "has", "had", "do", "does", "did", "will", "would",
  "shall", "should", "may", "might", "must", "can", "could",
  "not", "no", "nor", "and", "but", "or", "so", "if", "then",
  "than", "too", "very", "just", "also", "only",
  "in", "on", "at", "to", "for", "of", "with", "by", "from",
  "up", "about", "into", "through", "during", "before", "after",
  "above", "below", "between", "out", "off", "over", "under",
  "again", "further", "once", "here", "there", "when", "where",
  "why", "how", "all", "each", "every", "both", "few", "more",
  "most", "other", "some", "such", "any", "own", "same",
  "as", "until", "while", "because", "although", "since",
  "get", "got", "go", "going", "gone", "come", "came",
  "make", "made", "take", "took", "know", "knew", "think",
  "thought", "see", "saw", "want", "look", "use", "find",
  "give", "tell", "say", "said", "let", "put", "try",
  "need", "keep", "start", "show", "hear", "play", "run",
  "move", "like", "live", "believe", "hold", "bring",
  "happen", "write", "provide", "sit", "stand", "lose",
  "pay", "meet", "include", "continue", "set", "learn",
  "change", "lead", "understand", "watch", "follow", "stop",
  "create", "speak", "read", "allow", "add", "spend", "grow",
  "um", "uh", "like", "okay", "ok", "well", "right", "yeah",
  "yes", "no", "oh", "ah", "so", "actually", "basically",
  "really", "kind", "sort", "thing", "things", "stuff",
  "gonna", "gotta", "wanna",
  "something", "anything", "everything", "nothing",
  "someone", "anyone", "everyone", "one", "ones",
  "first", "two", "new", "way", "even", "much", "still",
  "back", "now", "long", "great", "little", "world",
  "good", "big", "old", "different", "lot", "able",
  "don", "doesn", "didn", "won", "wouldn", "couldn",
  "shouldn", "isn", "aren", "wasn", "weren", "hasn",
  "haven", "hadn", "don't", "doesn't", "didn't", "won't",
  "it's", "that's", "there's", "what's", "let's",
  "i'm", "i've", "i'll", "i'd", "we're", "we've", "we'll",
  "you're", "you've", "you'll", "you'd", "they're", "they've",
  "he's", "she's", "we'd", "they'll", "they'd",
]);

export function isStopword(word: string): boolean {
  return STOPWORDS.has(word) || word.length <= 1;
}
